version: 0.2

env:
  variables:
    BUILD_DIR: "dist"
    S3_BUCKET: "my-simple-static-site-cypress"
  parameter-store:
    AWS_ACCESS_KEY_ID: "/codebuild/key-id"
    AWS_SECRET_ACCESS_KEY: "/codebuild/key-secret"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
      - pip3 install awscli --upgrade --user
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync $BUILD_DIR s3://$S3_BUCKET --acl public-read

artifacts:
  files:
    - "**/*"
